Feature/tag instances
strofimovsky/aws-rolling-snaps pull request #5
Opened 2016-09-01 21:28 UTC by jxn

I didn't spend a lot of time on this, and I'm not _sure_ you'll want it, but I've added three features here:

1. the ability to tag the instances, rather then the volumes
2. when tagging the instances, the ability to limit to only running instances
3. the ability to pass a config file as an arg.  This is an easy way to configure different schedules for different tags, different aws accounts, different regions, etc.

If you want it and want changes, let me know.  Otherwise, I prefer you to close the PR rather than leaving it in limbo.  Thanks!

2016-09-20 19:34 UTC, strofimovsky requested changes
In the case of missing '-c' parameter, config_file would be set to None, default function params don't work that way. I suggest using argparse default in this case.

Also, now we don't need to check 'if len(sys.argv)>1', argparse does this for us.

2016-09-20 19:41 UTC, strofimovsky requested changes
get_vols() func exists  sys.exit(1) right after getting volume list, looks like some debug artefact or so.

also, I suggest throwing some exceptions than using sys.exit()

2016-09-20 19:43 UTC, strofimovsky commented
(I just got back from a trip) Awesome! Instance tagging is something I could use myselft right away!

2016-09-21 13:17 UTC, jxn commented
Thanks for the review.  I'll make changes and update the PR.

2016-09-22 04:07 UTC, jxn commented
@strofimovsky : Hopefully I've addressed your concerns.  Would you take another look and see if there's anything that needs to change?

2016-09-22 18:36 UTC, merged

2016-09-22 18:38 UTC, strofimovsky commented
Everything seems fine now. Thanks!